version: '2'
services:
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=SuperSecurePassword
      - MYSQL_DATABASE=fictional_computing_machine
      - MYSQL_USER=fictional
      - MYSQL_PASSWORD=Password1
    volumes:
      - /opt/data:/var/lib/mysql
  web:
    image: greeninja/fictional-computing-machine
    user: "100000"
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=fictional
      - DB_DATABASE=fictional_computing_machine
      - DB_PASSWORD=Password1
      - RAILS_ENV=development
    depends_on:
      - db
