# MySQL database config file
# Temp
development:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['DB_DATABASE'] || 'fictional_computing_machine' %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  pool: 5
  username: <%= ENV['DB_USER'] || 'fictional' %>
  password: <%= ENV['DB_PASS'] || 'Password1' %>

